CREATE TABLE users (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(100),
    PASSWORD_USER VARCHAR(100),
    PRIMARY KEY(ID)
);

INSERT INTO users(EMAIL, PASSWORD_USER)
VALUES ('teste@gmail.com', '12345');

